title: "Victorien De Meyer, PhD"
author: "Victorien De Meyer"
lang: "en"

permalink: /:title/

show_frame: true
show_sidebar: false
show_minimal: false

navigation:
  - {file: "index.md", title: "About"}
  - {file: "interests.md", title: "Interests"}
  - {file: "publications.md", title: "Publications"}
  - {file: "cv.md", title: "CV"}

external:
  - {title: Email, icon: envelope, url: "mailto:TON_EMAIL"}
  - {title: LinkedIn, icon: linkedin, url: "LIEN_LINKEDIN"}
  - {title: GitHub, icon: github, url: "https://github.com/VictorienDeMeyer"}
  - {title: ORCID, icon: orcid, url: "LIEN_ORCID"}

exclude:
  - README.md
